### ISSUE TITLE
docker run error: zeroconf.NoneUniqueNameException

### ISSUE THREAD

**Issue by Neustradamus** [openairplay/airplay2-receiver#17]
Originally: https://github.com/ckdo/airplay2-receiver/issues/7

@adrianzhang commented Sep 23, 2020

I git clone the source code and followed the instructions to create docker image and run it. However it gives me an error:

[root@mini airplay2-receiver]# docker run -it --rm --device /dev/snd --env AP2IFACE=enp1s0 --net host invano/ap2-receiver
[ ok ] Starting Avahi mDNS/DNS-SD Daemon: avahi-daemon.
Interface: enp1s0
IPv4: 192.168.1.5
IPv6: 240e:325:c:cf00:2e0:4cff:fe68:39b2

Traceback (most recent call last):
  File "ap2-receiver.py", line 737, in <module>
    mdns = register_mdns(args.mdns)
  File "ap2-receiver.py", line 659, in register_mdns
    zeroconf.register_service(info)
  File "/usr/local/lib/python3.7/dist-packages/zeroconf/__init__.py", line 2464, in register_service
    self.check_service(info, allow_name_change, cooperating_responders)
  File "/usr/local/lib/python3.7/dist-packages/zeroconf/__init__.py", line 2628, in check_service
    raise NonUniqueNameException
zeroconf.NonUniqueNameException

Don't worry about using root account, it is just a test computer. Thank you !

@adrianzhang commented Sep 23, 2020

There is a Airplay printer, other airplay android devices running in same network, however these clients working well.

**Comment by systemcrash** [comment]
I'm going to close this without further info. There have been a number of improvements to ZC recently, and main has tons of fixes also.

**Comment by Neustradamus** [comment]
@adrianzhang: It is good for you?
