### ISSUE TITLE
amixer: Unable to find simple control 'PCM',0

### ISSUE THREAD

**Issue by najihun** [openairplay/airplay2-receiver#48]
Thank you for contribution!

tried this receiver on my RP3, but got an issue as below.

Checked amixer on my RP3 there is only 'Master' not 'PCM'

Think if I could change the audio source(?), then docker can be run.

Is there any way to custom and fix ?

---------------------------------------------------------
amixer: Unable to find simple control 'PCM',0

Traceback (most recent call last):
  File "ap2-receiver.py", line 1108, in <module>
    setup_global_structs(args)
  File "ap2-receiver.py", line 273, in setup_global_structs
    volume = get_volume()
  File "/airplay2/ap2/utils.py", line 94, in get_volume
    line_pct = subprocess.check_output(["amixer", "get", "PCM"]).splitlines()[-1]
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['amixer', 'get', 'PCM']' returned non-zero exit status 1.

**Comment by tk97tk** [comment]
What was your solution? :)
