### ISSUE TITLE
RPI4 - Bullseye 64bit Issue or Container Issue (ver: Master)

### ISSUE THREAD

**Issue by NickJLange** [openairplay/airplay2-receiver#75]
### The problem

So having done a fresh clone/build with buildah using the Dockerfile on bullseye 64-bit (light) - I get the below error. After a bit of googling, there seems to be some major breakage in raspian between buster and bullseye releases which might be the issue? At any rate,  I wanted to raise the issue in case someone else stumbles across it - if I get some time I might dig deeper.  

### What commit exhibits the issue?

master

### Was there a last known working commit?

nope

### What type of installation are you running?

Docker

### With which python3 version do you run Receiver?

Docker version

### OS the receiver runs on

bullseye

### OS the sender runs

OSX

### Which sender client was used

Photos

### Command invocation

same as README.md

### Please include --debug output which helps to illustrate the problem

```
[ ok ] Starting Avahi mDNS/DNS-SD Daemon: avahi-daemon.
[Receiver]: Name: ap2
[Receiver]: Enabled features: 0001c300405f4200
[Receiver]: FeatureFlags.Ft48TransientPairing|Ft47PeerManagement|Ft46HomeKitPairing|Ft41_PTPClock|Ft40BufferedAudio|Ft30UnifiedAdvertisingInfo|Ft22AudioUnencrypted|Ft20ReceiveAudioAAC_LC|Ft19ReceiveAudioALAC|Ft18ReceiveAudioPCM|Ft17AudioMetaTxtDAAP|Ft16AudioMetaProgress|Ft14MFiSoft_FairPlay|Ft09AirPlayAudio
amixer: Mixer attach default error: No such file or directory
Traceback (most recent call last):
  File "ap2-receiver.py", line 1426, in <module>
    setup_global_structs(args, isDebug=DEBUG)
  File "ap2-receiver.py", line 202, in setup_global_structs
    volume = get_volume()
  File "/airplay2/ap2/utils.py", line 224, in get_volume
    line_pct = subprocess.check_output(["amixer", "get", "PCM"]).splitlines()[-1]
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['amixer', 'get', 'PCM']' returned non-zero exit status 1.
```

**Comment by Neustradamus** [comment]
@systemcrash, @LewdNeko: What do you think?

**Comment by Crazsped** [comment]
Also getting this error, but on Raspbian

**Comment by LewdNeko** [comment]
@Neustradamus I only have a Windows machine right now & am not experiencing issues. I won't be much help here 😅

**Comment by systemcrash** [comment]
is "headphone" a local modification for you, or one that applies globally for everyone on Linux?
